import fs from 'fs';

import { SVG_ICONS } from './svg-icons';

// Mapping from app icons to the actual exact name in plus-ui svgs
const mapping: Record<string, string> = {
  'home': 'home-2',
  'search': 'search-normal',
  'box': 'box',
  'heart': 'heart',
  'shopping-bag': 'shopping-bag',
  'bell': 'notification',
  'user': 'user',
  'chevron-left': 'arrow-left-2',
  'chevron-right': 'arrow-right-2',
  'chevron-down': 'arrow-down-2',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'arrow-up': 'arrow-up',
  'times': 'close-circle',
  'plus': 'add',
  'check': 'check',
  'trash': 'trash',
  'trash-alt': 'trash',
  'pen': 'edit-2',
  'edit': 'edit',
  'star': 'star',
  'star-outline': 'star',
  'map-marker': 'location',
  'map-marker-alt': 'location',
  'store': 'shop',
  'store-slash': 'shop-remove',
  'lock': 'lock',
  'unlock': 'unlock',
  'motorcycle': 'truck-fast', // fallback
  'truck': 'truck', // fallback if exists elsewhere
  'inbox': 'box',
  'ticket': 'ticket-2',
  'ticket-alt': 'ticket-2',
  'headset': 'headphone',
  'microphone': 'microphone',
  'stop': 'stop-circle', // Wait, maybe stop isn't needed
  'phone': 'call',
  'phone-alt': 'call',
  'images': 'gallery',
  'shield': 'shield-tick',
  'crown': 'crown',
  'camera': 'camera',
  'print': 'printer',
  'copy': 'copy',
  'info': 'info-circle',
  'info-circle': 'info-circle',
  'exclamation': 'warning-2',
  'exclamation-triangle': 'warning-2',
  'menu': 'menu',
  'eye': 'eye',
  'bars': 'menu',
  'shopping-cart': 'shopping-cart',
  'sign-out-alt': 'logout',
  'history': 'timer',
  'lightbulb': 'lamp',
  'bolt': 'flash',
  'sync-alt': 'refresh',
  'expand-alt': 'maximize',
  'cubes': '3dcube',
  'user-shield': 'user-tick',
  'user-cog': 'user-edit',
  'truck-moving': 'truck-fast', // fallback
  'truck-fast': 'truck-fast', // fallback
  'shield-check': 'shield-tick',
  'shield-virus': 'shield-cross',
  'shield-alt': 'shield-tick',
  'sliders-h': 'setting-4',
  'chart-line': 'chart',
  'undo': 'undo',
  'bullhorn': 'megaphone',
  'id-badge': 'card',
  'file-invoice-dollar': 'receipt-2',
  'file-csv': 'document',
  'user-slash': 'user-minus',
  'telegram-plane': 'send-2',
  'fire': 'flash',
  'bell-slash': 'notification-status',
  'box-open': 'box',
  'pause': 'pause',
  'smile': 'emoji-happy',
  'frown': 'emoji-sad',
  'list-ol': 'task',
  'link': 'link',
  'image': 'image',
  'cloud-upload': 'cloud-plus',
  'newspaper': 'document',
  'twitter': 'send-2',
  'wallet': 'wallet-2',
  'gift': 'gift',
  'percent': 'percentage-square',
  'credit-card-front': 'card',
  'mobile': 'mobile',
  'check-circle': 'tick-circle',
  'share-alt': 'share',
  'clock': 'clock',
  'gem': 'gemini-2',
  'coins': 'coin',
  'hourglass-half': 'timer',
  'database': 'data',
  'eye-slash': 'eye-slash',
  'save': 'save-2',
  'cloud-upload-alt': 'cloud-plus',
  'layer-group': 'layer',
  'users-cog': 'people',
  'comment-dots': 'message',
  'default': 'box'
};

// Check which mapping is invalid
const iconsAll = JSON.parse(fs.readFileSync('icons.json'));
const svgs = iconsAll.map(i => i.name);
const missing = Object.values(mapping).filter(v => !svgs.includes(v));
console.log(missing);
